name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on commits to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

    - name: Extract commit SHA for tagging
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and tag the Docker image
      run: |
        docker build -t my-flask-app:$IMAGE_TAG .
        docker tag my-flask-app:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
        docker tag my-flask-app:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Push Docker images to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
